name: Canary Build

on:
  push:
    branches:
      - master

jobs:
  canaryBuild:
    name: Canary Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[S]') && !contains(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Gradle Build
        run: |
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./gradlew assembleMinApi21Release
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk -name "*arm64-v8a*.apk")
#      - uses: actions/upload-artifact@v1
#        with:
#          name: NekoX Canary
#          path: ${{ env.APK_FILE }}
      - name: Upload Canary Apk
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.APK_FILE }}